services:
  db: 
    image: postgres:16.2-alpine3.19
    container_name: postgres-db
    environment:
      POSTGRES_USER: user-products
      POSTGRES_PASSWORD: 2000
      POSTGRES_DB: db-products 
    ports:
      - 3216:5432
    volumes:
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    ports:
      - 3836:8080